apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sandbox-platform.fullname" . }}
  labels:
    app: {{ include "sandbox-platform.fullname" . }}
type: Opaque
stringData:
  OPENSANDBOX_API_KEY: {{ .Values.secrets.opensandboxApiKey | quote }}
